apiVersion: v1
kind: Service
metadata:
  name: person
  namespace: demo
  labels:
    type: service
    version: v1
spec:
  selector:
    app: person
    type: pod
    version: v1
  ports:
  - port: 9000
    targetPort: 8090
