apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  namespace: demo
  labels:
    type: deployment
    version: v1
spec:
  selector:
    matchLabels:
      app: location
      type: pod
      version: v1
  template:
    metadata:
      labels:
        app: location
        type: pod
        version: v1
    spec:
      containers:
      - name: location
        image: locationserver:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8091
